### ISSUE TITLE
references to tstanley

### ISSUE THREAD

**Issue by selhorn** [tstanley93/cloud-month#1]
I think you need to upload this zip and make the link relative? (Will break when we move the cft?)

C:\\Users\\Administrator\\Downloads\\webpage.zip": {
                                "source": "https://raw.githubusercontent.com/tstanley93/cloud-month/master/webpage.zip"

**Comment by tstanley93** [comment]
Yes this will be fixed when we move this to the new repository ... but it cannot be relative since it is downloaded ...
