### ISSUE TITLE
Instances don't have Name populated

### ISSUE THREAD

**Issue by selhorn** [tstanley93/cloud-month#2]
Can we add tag names for the instances? I can't tell which is which (without clicking each individual instance). (I entered the names in the template so I'm assuming they just didn't get assigned...)
![image](https://cloud.githubusercontent.com/assets/19737976/26216195/0d9a1110-3bb8-11e7-8393-6635d1dc04b2.png)

**Comment by tstanley93** [comment]
Yes I will set the Name tag on the left hand side to name them ...

**Comment by tstanley93** [comment]
merge pushed ... testing next ...

**Comment by tstanley93** [comment]
Tested ... tags are now working for all of the instances ...
