### ISSUE TITLE
2 of 3 instances not available

### ISSUE THREAD

**Issue by selhorn** [tstanley93/cloud-month#4]
The first instance is running fine. All 3 instances were added behind the load balancer, but two are out of service and I can't access via their elastic IPs.
![image](https://cloud.githubusercontent.com/assets/19737976/26216468/103a0582-3bb9-11e7-9bc6-d1a2539621a7.png)

**Comment by selhorn** [comment]
I remoted in to the instances and can see they don't have IIS installed.

**Comment by selhorn** [comment]
OK I checked in a fix for this one. I will leave the others to you.

**Comment by tstanley93** [comment]
I merged ... closing this issue
