### ISSUE TITLE
Admin user wasn't added to local administrators group

### ISSUE THREAD

**Issue by selhorn** [tstanley93/cloud-month#6]
Not sure if this is causing a problem but I think it is. See the comma after password? (This occurs three times, once for each Windows instance.) I think that comma should be removed, or add one after username? I could RDP to the instance with the password I specified, but had to use username Administrator rather than the unique admin name I specified.

                                            "param (\n",    
                                            "  [string]$password,\n",
                                            "   [string]$username\n",

**Comment by tstanley93** [comment]
The syntax with the comma is correct ... but something further down in script must be broken ... I will look into it.

**Comment by tstanley93** [comment]
I have checked in and tested ... you can now login to each of the instances with the username and password that you specified in the template ...
